steps:
  # Steps to build the Docker image using the Dockerfile in the repository
  - id: 'Build'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/${PROJECT_ID}/loan-eligibility:latest', '.']

  # Steps to push the built Docker image to the Google Container Registry (GCR) in the Asia region
  - id: 'Push'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/${PROJECT_ID}/loan-eligibility:latest']

options:
  logging: CLOUD_LOGGING_ONLY
